version: 0.0
os: linux
files:
  - source: /server.js
    destination: /home/ec2-user/acta-twilio
  - source: /package.json
    destination: /home/ec2-user/acta-twilio
  - source: /node_modules
    destination: /home/ec2-user/acta-twilio/node_modules
  - source: /config
    destination: /home/ec2-user/acta-twilio/config
  - source: /routes
    destination: /home/ec2-user/acta-twilio/routes
  - source: /views
    destination: /home/ec2-user/acta-twilio/views
  - source: /public
    destination: /home/ec2-user/acta-twilio/public
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
